_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
budget:
    value: 10000
episodes:
    value: 2
max_steps:
    value: 10
update_fq:
    value: 5
use_wandb:
    value: true
verbose:
    value: true
